# Generated by Django 4.2.6 on 2023-10-30 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Artist name')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)], verbose_name='Year')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.musicgenre', verbose_name='Genre')),
            ],
        ),
    ]
